### ISSUE TITLE
New to GitHub

### ISSUE THREAD

**Issue by liviuslivius** [Wilyb/Wily-bit-s-GTNH-tex#4]
Hey,
love ur pack. But i have no idea how to download it for ingame use. 

Thanks for an Response

Livius

**Comment by mainrs** [comment]
You go to the "homepage" of the repository: https://github.com/Wilyb/Wily-bit-s-GTNH-tex.
On the right sidebar there will be a green tag symbol that links you to the latest release. In this case the link will be:
https://github.com/Wilyb/Wily-bit-s-GTNH-tex/releases/tag/V.0.0.2

There you'll find a file attachment that you can download and put into your resourcepacks folder.

**Comment by liviuslivius** [comment]
Thx

**Comment by liviuslivius** [comment]
It worked

**Comment by liviuslivius** [comment]
Sorry. The download worked but minecraft does not recognice the file as a ressource pack.

**Comment by mainrs** [comment]
Ahhh, my bad! The zip file seems to contain a folder named the same as this repository. This means that you have to unzip the file inside the `resourcepacks` folder. Minecraft does also recognize folders as resource packs.

Your final folder structure should be `resourcepacks/Wily bit GTNH tex/{assets,pack.mcmeta}`. I.e., there is a folder named `Wily bit GTNH tex` containing a folder named `assets`, a file named `pack.mcmeta` and optionally other things.

Lemme know if that works!

**Comment by liviuslivius** [comment]
That worked thanks a lot

**Comment by liviuslivius** [comment]
Dude i LOVE the pack its amazing. Any chance u could add a glowing effect to the ebf coils as a future update?
